services:
  fados.calendar.service:
       class:  Kronhyx\fullCalendarBundle\Services\CalendarManagerRegistry
       arguments: ["@doctrine","@service_container", "@event_dispatcher"]
  app.fados.twig_extension:
       class:  Kronhyx\fullCalendarBundle\Twig\fullCalendarExtension
       public: false
       tags:
         - { name: twig.extension }

